meta_product_name: "Giftapes"
meta_title: "Share gifts with meaning!"
meta_description: "Share gifts with meaning!"
meta_image: "https://res.cloudinary.com/susanjsp/image/upload/v1607558855/logo-final.png" # should exist in `app/assets/images/`
